// examples/devtools/src/App.tsx
import { useState, useEffect, FormEvent, Component, ReactNode } from "react";
import { createClient, ServerError, TransportError, StreamState } from "@tygor/client";
import { registry } from "./rpc/manifest";
import type { Task, TimeUpdate } from "./rpc/types";

const client = createClient(registry, {
  baseUrl: "/api",
});

interface AppError {
  type: "server" | "transport" | "unknown";
  code?: string;
  message: string;
}

function toAppError(e: unknown): AppError {
  if (e instanceof ServerError) {
    return { type: "server", code: e.code, message: e.message };
  }
  if (e instanceof TransportError) {
    return { type: "transport", message: e.message };
  }
  return { type: "unknown", message: e instanceof Error ? e.message : "Unknown error" };
}

// ErrorBoundary for catching render errors
interface ErrorBoundaryState {
  error: Error | null;
}

class ErrorBoundary extends Component<{ children: ReactNode }, ErrorBoundaryState> {
  state: ErrorBoundaryState = { error: null };

  static getDerivedStateFromError(error: Error) {
    return { error };
  }

  render() {
    if (this.state.error) {
      return (
        <div style={{ padding: 20, background: "#fee2e2", color: "#991b1b", borderRadius: 4, margin: 16 }}>
          <strong>React Error</strong>
          <pre style={{ margin: "8px 0 0", fontSize: 12, whiteSpace: "pre-wrap" }}>
            {this.state.error.message}
          </pre>
          <button
            onClick={() => this.setState({ error: null })}
            style={{ marginTop: 8, fontSize: 12, padding: "4px 8px" }}
          >
            Try again
          </button>
        </div>
      );
    }
    return this.props.children;
  }
}

export default function App() {
  const [tasks, setTasks] = useState<(Task | null)[]>([]);
  const [newTask, setNewTask] = useState("");
  const [error, setError] = useState<AppError | null>(null);
  const [time, setTime] = useState<TimeUpdate | null>(null);
  const [tasksState, setTasksState] = useState<StreamState | null>(null);

  // Subscribe to synced task list - automatically updates across all browser windows
  const { data: tasksData, state: tasksStateAtom } = client.Tasks.SyncedList;
  useEffect(() => tasksData.subscribe(setTasks), []);
  useEffect(() => tasksStateAtom.subscribe(setTasksState), []);

  // Subscribe to time stream
  const timeStream = client.Tasks.Time({});
  useEffect(() => timeStream.data.subscribe(setTime), []);


  const handleCreate = async (e: FormEvent) => {
    e.preventDefault();
    if (!newTask.trim()) return;
    try {
      await client.Tasks.Create({ title: newTask });
      setNewTask("");
      setError(null);
    } catch (e) {
      setError(toAppError(e));
    }
  };

  const handleToggle = async (id: number) => {
    try {
      await client.Tasks.Toggle({ id });
      setError(null);
    } catch (e) {
      setError(toAppError(e));
    }
  };

  return (
    <ErrorBoundary>
      <div>
        {error && (
          <div className="info" style={{ background: "#fff3cd", color: "#856404" }}>
            <strong>{error.type}</strong>
            {error.code && <code style={{ marginLeft: 8, marginRight: 8, background: "rgba(0,0,0,0.1)", padding: "2px 6px", borderRadius: 3 }}>{error.code}</code>}
            <span style={{ marginLeft: 8 }}>{error.message}</span>
          </div>
        )}
        <button onClick={() => client.Tasks.MakeError().catch((e) => setError(toAppError(e)))} style={{ fontSize: "0.7rem", padding: "2px 6px" }}>
          Make an error
        </button>

        <h1>Tasks</h1>
        {tasksState && (
          <div style={{ fontSize: "0.7rem", color: tasksState.status === "connected" ? "#16a34a" : "#ca8a04", marginBottom: 8 }}>
            {tasksState.status === "connected" ? "●" : tasksState.status === "connecting" ? "○" : "◌"} {tasksState.status}
          </div>
        )}
        {time && (
          <div style={{ fontSize: "0.8rem", color: "#666", marginBottom: 12, fontVariantNumeric: "tabular-nums" }}>
            Server time: {new Date(time.time).toLocaleTimeString()}{" "}
            <span style={{ opacity: 0.6 }}>(via Tasks.Time SSE)</span>
          </div>
        )}
        <form onSubmit={handleCreate}>
          <input
            value={newTask}
            onChange={(e) => setNewTask(e.target.value)}
            placeholder="New task..."
          />
          <button type="submit">Add</button>
        </form>
        <ul>
          {tasks.filter((t): t is Task => t !== null).map((task) => (
            <li
              key={task.id}
              className={task.done ? "done" : ""}
              onClick={() => handleToggle(task.id)}
            >
              {task.done ? "✓" : "○"} {task.title}
            </li>
          ))}
        </ul>
      </div>
    </ErrorBoundary>
  );
}

// examples/starter-solid/src/App.tsx
import { createSignal, onMount, onCleanup } from "solid-js";
import { createClient, ServerError, ValidationError, type StreamState } from "@tygor/client";
import { registry } from "./rpc/manifest";
import { schemaMap } from "./rpc/schemas.map.zod";
import type { MessageState } from "./rpc/types";

const client = createClient(registry, {
  baseUrl: "/api",
  schemas: schemaMap,
  validate: { request: true },
});

function formatError(err: unknown): string {
  if (err instanceof ValidationError) {
    // Client-side validation error - format the zod issues
    const messages = err.issues.map((issue) => {
      const path = issue.path?.join(".") ?? "";
      return path ? `${path}: ${issue.message}` : issue.message;
    });
    return messages.join("; ");
  }
  if (err instanceof ServerError) {
    return err.message;
  }
  return err instanceof Error ? err.message : "Unknown error";
}

export default function App() {
  const [state, setState] = createSignal<MessageState | null>(null);
  const [connectionState, setConnectionState] = createSignal<StreamState | null>(null);
  const [input, setInput] = createSignal("");
  const [error, setError] = createSignal<string | null>(null);

  // Subscribe to the atom - get current value and updates
  onMount(() => {
    const atom = client.Message.State;
    const unsub = atom.data.subscribe(setState);
    const unsubState = atom.state.subscribe(setConnectionState);
    onCleanup(() => {
      unsub();
      unsubState();
    });
  });

  const handleSet = async (e: Event) => {
    e.preventDefault();
    setError(null);
    try {
      await client.Message.Set({ message: input() });
      setInput("");
    } catch (err) {
      setError(formatError(err));
    }
  };

  return (
    <div>
      <h1>Message Atom</h1>

      {connectionState() && (
        <div style={{ "font-size": "0.75rem", color: connectionState()!.status === "connected" ? "#16a34a" : "#ca8a04", "margin-bottom": "1rem" }}>
          {connectionState()!.status === "connected" ? "\u25CF" : connectionState()!.status === "connecting" ? "\u25CB" : "\u25CC"} {connectionState()!.status}
        </div>
      )}

      {state() && (
        <div style={{ "margin-bottom": "1rem" }}>
          <div style={{ "font-size": "2rem", "font-weight": "bold" }}>{state()!.message}</div>
          <div style={{ "font-size": "0.875rem", color: "#666" }}>
            Set {state()!.set_count} time{state()!.set_count !== 1 ? "s" : ""}
          </div>
        </div>
      )}

      <form onSubmit={handleSet}>
        <input
          value={input()}
          onInput={(e) => setInput(e.currentTarget.value)}
          placeholder="5-10 characters..."
          minLength={5}
          maxLength={10}
        />
        <button type="submit">Set</button>
      </form>

      {error() && (
        <div style={{ color: "#dc2626", "margin-top": "0.5rem", "font-size": "0.875rem" }}>
          {error()}
        </div>
      )}

      <p style={{ "font-size": "0.75rem", color: "#999", "margin-top": "2rem" }}>
        Open this page in multiple tabs - they all sync via the Atom!
      </p>
    </div>
  );
}
